/**
 * @generated
 * @file Navigation (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://pawsitive-training-a9f6b6.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import DOM from "./webflow_modules/Builtin/components/DOM";
import DropdownList from "./webflow_modules/Dropdown/components/DropdownList";
import DropdownToggle from "./webflow_modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "./webflow_modules/Dropdown/components/DropdownWrapper";
import Grid from "./webflow_modules/Layout/components/Grid";
import Icon from "./webflow_modules/Icon/components/Icon";
import Link from "./webflow_modules/Basic/components/Link";
import List from "./webflow_modules/Basic/components/List";
import ListItem from "./webflow_modules/Basic/components/ListItem";
import NavbarButton from "./webflow_modules/Navbar/components/NavbarButton";
import NavbarMenu from "./webflow_modules/Navbar/components/NavbarMenu";
import NavbarWrapper from "./webflow_modules/Navbar/components/NavbarWrapper";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Strong from "./webflow_modules/Basic/components/Strong";

/**
 * Props for {@link Navigation}
 */
export type NavigationProps = {};

/**
 * Navigation
 *
 * @see {@link https://pawsitive-training-a9f6b6.design.webflow.com | Source site in Webflow}
 */
export function Navigation({}: NavigationProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className="nav is-inverse" tag="div">
        <NavbarWrapper
          className="nav_container"
          config={{
            easing: "ease",
            easing2: "ease",
            duration: 400,
            docHeight: false,
            noScroll: true,
            animation: "default",
            collapse: "medium",
          }}
          data-animation="default"
          data-collapse="medium"
          data-duration="400"
          data-easing="ease"
          data-easing2="ease"
          data-no-scroll="1"
          role="banner"
          tag="div"
        >
          <Block
            className="nav_left"
            id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c39b-aeafab6e"
            tag="div"
          >
            <Link
              block="inline"
              button={false}
              className="nav_logo"
              id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c2eb-aeafab6e"
              options={{
                href: "#",
              }}
            >
              <Block className="nav_logo-icon" tag="div">
                <DOM
                  height="100%"
                  preserveAspectRatio="xMidYMid meet"
                  slot=""
                  tag="svg"
                  viewBox="0 0 33 33"
                  width="100%"
                >
                  <DOM
                    d="M28,0H5C2.24,0,0,2.24,0,5v23c0,2.76,2.24,5,5,5h23c2.76,0,5-2.24,5-5V5c0-2.76-2.24-5-5-5ZM29,17c-6.63,0-12,5.37-12,12h-1c0-6.63-5.37-12-12-12v-1c6.63,0,12-5.37,12-12h1c0,6.63,5.37,12,12,12v1Z"
                    fill="currentColor"
                    slot=""
                    tag="path"
                  />
                </DOM>
              </Block>
              <Block
                className="paragraph_large margin-bottom_none"
                data-brand-name="true"
                tag="div"
              >
                {"Pawsitive Training"}
              </Block>
            </Link>
            <NavbarMenu
              className="nav_menu"
              id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c39a-aeafab6e"
              role="navigation"
              tag="nav"
            >
              <List
                className="nav_menu-list"
                role="list"
                tag="ul"
                unstyled={true}
              >
                <ListItem className="nav_menu-list-item">
                  <DropdownWrapper
                    className="nav_dropdown-menu"
                    delay={0}
                    hover={false}
                    tag="div"
                  >
                    <DropdownToggle className="nav_link on-inverse" tag="div">
                      <Block tag="div">{"Services"}</Block>
                      <Icon
                        className="nav_caret"
                        widget={{
                          type: "icon",
                          icon: "dropdown-toggle",
                        }}
                      />
                    </DropdownToggle>
                    <DropdownList className="mega-nav_dropdown-list" tag="nav">
                      <Block
                        className="mega-nav_dropdown-list-wrapper"
                        tag="div"
                      >
                        <List
                          className="grid_3-col tablet-1-col-1 gap-medium margin-bottom_none"
                          role="list"
                          tag="ul"
                          unstyled={true}
                        >
                          <ListItem
                            className="grid-item-manual w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c36b-aeafab6e"
                            id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc0fc-4d562d54"
                          >
                            <Grid className="grid_3-col tablet-1-col-1 gap-small">
                              <Block className="grid-item-manual" tag="div">
                                <Block className="eyebrow" tag="div">
                                  {"Training Programs"}
                                </Block>
                                <List
                                  className="mega-nav_list"
                                  role="list"
                                  tag="ul"
                                  unstyled={true}
                                >
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c2ff-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c2fd-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc107-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"Puppy Basics"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"Start your puppy"}
                                            {"’"}
                                            {"s training journey."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c30b-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c309-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc113-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"Obedience Classes"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"Group sessions for all ages."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c317-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c315-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc11f-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"Private Lessons"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"One-on-one tailored support."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                </List>
                              </Block>
                              <Block
                                className="grid-item-manual"
                                id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c341-aeafab6e"
                                tag="div"
                              >
                                <Block className="eyebrow" tag="div">
                                  {"Behavior Solutions"}
                                </Block>
                                <List
                                  className="mega-nav_list"
                                  role="list"
                                  tag="ul"
                                  unstyled={true}
                                >
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c327-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c325-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc12f-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"Problem Solving"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"Address common behavior issues."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c333-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c331-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc13b-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"Socialization"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"Safe group play and learning."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c33f-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c33d-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc147-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"Advanced Skills"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"Take training to the next level."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                </List>
                              </Block>
                              <Block
                                className="grid-item-manual"
                                id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c369-aeafab6e"
                                tag="div"
                              >
                                <Block className="eyebrow" tag="div">
                                  {"Resources"}
                                </Block>
                                <List
                                  className="mega-nav_list"
                                  role="list"
                                  tag="ul"
                                  unstyled={true}
                                >
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c34f-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c34d-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc157-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"FAQs"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"Answers to common questions."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c35b-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c359-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc163-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"Blog"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"Tips and training advice."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c367-aeafab6e">
                                    <Link
                                      block="inline"
                                      button={false}
                                      className="mega-nav_link-item"
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className="nav_icon is-medium"
                                        tag="div"
                                      >
                                        <DOM
                                          fill="currentColor"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 32 32"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            slot=""
                                            stroke-linejoin="round"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className="content-block w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c365-aeafab6e"
                                        id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc16f-4d562d54"
                                        tag="div"
                                      >
                                        <Block tag="div">
                                          <Strong>{"Contact"}</Strong>
                                        </Block>
                                        <Block
                                          className="text-color_primary"
                                          tag="div"
                                        >
                                          <Block
                                            className="paragraph_small text-color_secondary"
                                            tag="div"
                                          >
                                            {"Get in touch with our team."}
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                </List>
                              </Block>
                            </Grid>
                          </ListItem>
                          <ListItem
                            className="grid-item-manual w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c37a-aeafab6e"
                            id="w-node-_79ea5404-da65-bca7-0d45-4bb38bebc176-4d562d54"
                          >
                            <Link
                              block="inline"
                              button={false}
                              className="card-link is-inverse on-inverse"
                              options={{
                                href: "#",
                              }}
                            >
                              <Block className="card_body" tag="div">
                                <Block className="heading_tertiary" tag="div">
                                  {"Expert trainers. Real results."}
                                </Block>
                                <Paragraph className="paragraph_small text-color_inverse-secondary">
                                  {
                                    "Meet our certified trainers and discover how we help dogs and owners succeed together."
                                  }
                                </Paragraph>
                                <Block className="margin_top-auto" tag="div">
                                  <Block className="button-group" tag="div">
                                    <Block
                                      className="text-button is-secondary on-inverse"
                                      tag="div"
                                    >
                                      <Block tag="div">{"Meet team"}</Block>
                                      <Block className="button_icon" tag="div">
                                        <DOM
                                          fill="none"
                                          height="100%"
                                          slot=""
                                          tag="svg"
                                          viewBox="0 0 16 16"
                                          width="100%"
                                          xmlns="http://www.w3.org/2000/svg"
                                        >
                                          <DOM
                                            d="M2 8H14.5M14.5 8L8.5 2M14.5 8L8.5 14"
                                            slot=""
                                            stroke="currentColor"
                                            stroke-linejoin="round"
                                            stroke-width="2"
                                            tag="path"
                                          />
                                        </DOM>
                                      </Block>
                                    </Block>
                                  </Block>
                                </Block>
                              </Block>
                            </Link>
                          </ListItem>
                        </List>
                      </Block>
                    </DropdownList>
                  </DropdownWrapper>
                </ListItem>
                <ListItem className="nav_menu-list-item">
                  <Link
                    block="inline"
                    button={false}
                    className="nav_link on-inverse"
                    options={{
                      href: "#",
                    }}
                  >
                    <Block tag="div">{"About"}</Block>
                  </Link>
                </ListItem>
                <ListItem className="nav_menu-list-item">
                  <Link
                    block="inline"
                    button={false}
                    className="nav_link on-inverse"
                    options={{
                      href: "#",
                    }}
                  >
                    <Block tag="div">{"Blog"}</Block>
                  </Link>
                </ListItem>
                <ListItem className="nav_menu-list-item">
                  <DropdownWrapper
                    className="nav_dropdown-menu"
                    delay={0}
                    hover={false}
                    tag="div"
                  >
                    <DropdownToggle className="nav_link on-inverse" tag="div">
                      <Block tag="div">{"Support"}</Block>
                      <Icon
                        className="nav_caret"
                        widget={{
                          type: "icon",
                          icon: "dropdown-toggle",
                        }}
                      />
                    </DropdownToggle>
                    <DropdownList className="nav_dropdown-list-1" tag="div">
                      <Block
                        className="nav-menu_dropdown-list-wrapper"
                        tag="div"
                      >
                        <List
                          className="flex_vertical margin-bottom_none"
                          role="list"
                          tag="ul"
                          unstyled={true}
                        >
                          <ListItem className="margin-bottom_none">
                            <Link
                              block="inline"
                              button={false}
                              className="nav_dropdown-link"
                              options={{
                                href: "#",
                              }}
                            >
                              <Block className="button_label" tag="div">
                                {"Help center"}
                              </Block>
                            </Link>
                          </ListItem>
                          <ListItem className="margin-bottom_none">
                            <Link
                              block="inline"
                              button={false}
                              className="nav_dropdown-link"
                              options={{
                                href: "#",
                              }}
                            >
                              <Block className="button_label" tag="div">
                                {"Contact us"}
                              </Block>
                            </Link>
                          </ListItem>
                        </List>
                      </Block>
                    </DropdownList>
                  </DropdownWrapper>
                </ListItem>
              </List>
            </NavbarMenu>
          </Block>
          <Block
            className="nav_right"
            id="w-node-_98b2c4b2-24c1-f743-8891-5a5e6f44c3a0-aeafab6e"
            tag="div"
          >
            <Block className="button-group margin-top_none" tag="div">
              <Link
                block="inline"
                button={false}
                className="button on-inverse"
                options={{
                  href: "#",
                }}
              >
                <Block className="button_label" tag="div">
                  {"Book now"}
                </Block>
              </Link>
            </Block>
          </Block>
          <NavbarButton className="nav_mobile-menu-button" tag="div">
            <Block className="icon on-inverse" tag="div">
              <DOM
                height="24"
                slot=""
                tag="svg"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <DOM
                  class="nc-icon-wrapper"
                  fill="none"
                  slot=""
                  stroke="currentColor"
                  stroke-linecap="square"
                  stroke-linejoin="miter"
                  stroke-miterlimit="10"
                  stroke-width="1.5"
                  tag="g"
                >
                  <DOM
                    slot=""
                    stroke="currentColor"
                    tag="line"
                    x1="1"
                    x2="23"
                    y1="12"
                    y2="12"
                  />
                  <DOM slot="" tag="line" x1="1" x2="23" y1="5" y2="5" />
                  <DOM slot="" tag="line" x1="1" x2="23" y1="19" y2="19" />
                </DOM>
              </DOM>
            </Block>
          </NavbarButton>
        </NavbarWrapper>
      </Block>
    </div>
  );
}
